language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_install:
  - pecl install mongodb > /dev/null

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - if [[ $(phpenv version-name) = "7.3" ]]; then php vendor/bin/php-coveralls -v; fi
