version: '3'

services:
  php:
    build: docker/php
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db

  db:
    image: mongo:4.2
    volumes:
      - db:/data/db

volumes:
  db:
    driver: local
